<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Series extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Series_model');
    } 

    /*
     * Listing of series
     */
    function index()
    {
        $data['series'] = $this->Series_model->get_all_series();
		
		$this->load->view('templates/header');
        $this->load->view('series/index',$data);
		$this->load->view('templates/footer');
    }

    /*
     * Adding a new series
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('series_title','Series Title','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'series_title' => $this->input->post('series_title'),
            );
            
            $series_id = $this->Series_model->add_series($params);
            redirect('series/index');
        }
        else
        {
			$this->load->view('templates/header');
            $this->load->view('series/add');
			$this->load->view('templates/footer');
        }
    }  

    /*
     * Editing a series
     */
    function edit($series_id)
    {   
        // check if the series exists before trying to edit it
        $data['series'] = $this->Series_model->get_series($series_id);
        
        if(isset($data['series']['series_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('series_title','Series Title','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'series_title' => $this->input->post('series_title'),
                );

                $this->Series_model->update_series($series_id,$params);            
                redirect('series/index');
            }
            else
            {
				$this->load->view('templates/header');
                $this->load->view('series/edit',$data);
				$this->load->view('templates/footer');
            }
        }
        else
            show_error('The series you are trying to edit does not exist.');
    } 

    /*
     * Deleting series
     */
    function remove($series_id)
    {
        $series = $this->Series_model->get_series($series_id);

        // check if the series exists before trying to delete it
        if(isset($series['series_id']))
        {
            $this->Series_model->delete_series($series_id);
            redirect('series/index');
        }
        else
            show_error('The series you are trying to delete does not exist.');
    }
    
}
