<?php
/*
 * Generated by CRUDigniter v3.0 Beta
 * www.crudigniter.com
 */

class Note_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get latest note
     */
  	function get_latest_note()
  	{
      $this->db->order_by('note_date');
      return $this->db->get('notes' , 1)->result_array();    
  	}

    /*
     * Get note by note_id
     */
    function get_note($note_id)
    {
		return $this->db->get_where('notes',array('note_id'=>$note_id))->row_array();
    }

    /*
     * Get all notes
     */
    function get_all_notes()
    {
        return $this->db->get('notes')->result_array();
    }

    /*
     * function to add new note
     */
    function add_note($params)
    {
        $this->db->insert('notes',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update note
     */
    function update_note($note_id,$params)
    {
        $this->db->where('note_id',$note_id);
        $response = $this->db->update('notes',$params);
        if($response)
        {
            return "note updated successfully";
        }
        else
        {
            return "Error occuring while updating note";
        }
    }

    /*
     * function to delete note
     */
    function delete_note($note_id)
    {
        $response = $this->db->delete('notes',array('note_id'=>$note_id));
        if($response)
        {
            return "note deleted successfully";
        }
        else
        {
            return "Error occuring while deleting note";
        }
    }
}
