<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Series_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get series by series_id
     */
    function get_series($series_id)
    {
        return $this->db->get_where('series',array('series_id'=>$series_id))->row_array();
    }
    
    /*
     * Get all series
     */
    function get_all_series()
    {
        return $this->db->get('series')->result_array();
    }
    
    /*
     * function to add new series
     */
    function add_series($params)
    {
        $this->db->insert('series',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update series
     */
    function update_series($series_id,$params)
    {
        $this->db->where('series_id',$series_id);
        $response = $this->db->update('series',$params);
        if($response)
        {
            return "series updated successfully";
        }
        else
        {
            return "Error occuring while updating series";
        }
    }
    
    /*
     * function to delete series
     */
    function delete_series($series_id)
    {
        $response = $this->db->delete('series',array('series_id'=>$series_id));
        if($response)
        {
            return "series deleted successfully";
        }
        else
        {
            return "Error occuring while deleting series";
        }
    }
}
