<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Speaker_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get speaker by speaker_id
     */
    function get_speaker($speaker_id)
    {
        $speaker = $this->db->query("
            SELECT
                *

            FROM
                `speaker`

            WHERE
                `speaker_id` = ?
        ",array($speaker_id))->row_array();

        return $speaker;
    }
    
    /*
     * Get all speaker
     */
    function get_all_speaker()
    {
        $speaker = $this->db->query("
            SELECT
                *

            FROM
                `speaker`

            WHERE
                1 = 1
        ")->result_array();

        return $speaker;
    }
    
    /*
     * function to add new speaker
     */
    function add_speaker($params)
    {
        $this->db->insert('speaker',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update speaker
     */
    function update_speaker($speaker_id,$params)
    {
        $this->db->where('speaker_id',$speaker_id);
        $response = $this->db->update('speaker',$params);
        if($response)
        {
            return "speaker updated successfully";
        }
        else
        {
            return "Error occuring while updating speaker";
        }
    }
    
    /*
     * function to delete speaker
     */
    function delete_speaker($speaker_id)
    {
        $response = $this->db->delete('speaker',array('speaker_id'=>$speaker_id));
        if($response)
        {
            return "speaker deleted successfully";
        }
        else
        {
            return "Error occuring while deleting speaker";
        }
    }
}
